name: arrowdev
channels:
  - conda-forge                     # We added a third party channel
  - defaults
dependencies:
  - pandas
  - python=3.9
  - jupyter
  # have to use pip for pyarrow, numpy and pybind11, 
  # `conda install` keep .so and header files in different locations 
  # than `pip install`
  - pip:
    - pyarrow==7.0
    - numpy
    - pybind11

